/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors for retro themes will be defined via CSS variables
      },
      fontFamily: {
        'mono': ['Courier New', 'Courier', 'monospace'],
        'sans': ['Arial', 'Helvetica', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        basic: {
          "primary": "#333333",
          "primary-content": "#ffffff",
          "secondary": "#ffffff",
          "secondary-content": "#333333",
          "accent": "#333333",
          "accent-content": "#ffffff",
          "neutral": "#f5f5f5",
          "neutral-content": "#333333",
          "base-100": "#ffffff",
          "base-200": "#f9f9f9",
          "base-300": "#f5f5f5",
          "base-content": "#333333",
          "info": "#333333",
          "info-content": "#ffffff",
          "success": "#00aa00",
          "success-content": "#ffffff",
          "warning": "#ffaa00",
          "warning-content": "#000000",
          "error": "#cc0000",
          "error-content": "#ffffff",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "1rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
        },
        "terminal-green": {
          "primary": "#00ff00",
          "primary-content": "#000000",
          "secondary": "#008800",
          "secondary-content": "#00ff00",
          "accent": "#00ff00",
          "accent-content": "#000000",
          "neutral": "#001100",
          "neutral-content": "#00ff00",
          "base-100": "#000000",
          "base-200": "#001100",
          "base-300": "#002200",
          "base-content": "#00ff00",
          "info": "#00ff00",
          "info-content": "#000000",
          "success": "#00ff00",
          "success-content": "#000000",
          "warning": "#ffff00",
          "warning-content": "#000000",
          "error": "#ff0000",
          "error-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
        },
        cyberpunk: {
          "primary": "#00ffff",
          "primary-content": "#0a0e27",
          "secondary": "#ff00ff",
          "secondary-content": "#0a0e27",
          "accent": "#00ffff",
          "accent-content": "#0a0e27",
          "neutral": "#0a0e27",
          "neutral-content": "#00ffff",
          "base-100": "#0a0e27",
          "base-200": "#141933",
          "base-300": "#1e2440",
          "base-content": "#00ffff",
          "info": "#00ffff",
          "info-content": "#0a0e27",
          "success": "#00ff00",
          "success-content": "#0a0e27",
          "warning": "#ffff00",
          "warning-content": "#0a0e27",
          "error": "#ff0066",
          "error-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
        },
        amber: {
          "primary": "#ffb000",
          "primary-content": "#1a0f00",
          "secondary": "#cc8800",
          "secondary-content": "#1a0f00",
          "accent": "#ffb000",
          "accent-content": "#1a0f00",
          "neutral": "#1a0f00",
          "neutral-content": "#ffb000",
          "base-100": "#1a0f00",
          "base-200": "#2a1f00",
          "base-300": "#3a2f00",
          "base-content": "#ffb000",
          "info": "#ffb000",
          "info-content": "#1a0f00",
          "success": "#ffaa00",
          "success-content": "#1a0f00",
          "warning": "#ffcc00",
          "warning-content": "#1a0f00",
          "error": "#ff6600",
          "error-content": "#ffffff",
          "--rounded-box": "0",
          "--rounded-btn": "0",
          "--rounded-badge": "0",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-text-case": "none",
          "--border-btn": "1px",
        },
      },
    ],
  },
}
